//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedEditorProg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedEditorProg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,0,0
        ///A,4,44
        ///B,5,45
        ///C,6,46
        ///D,7,47
        ///E,8,48
        ///F,9,49
        ///G,10,50
        ///H,11,51
        ///I,12,52
        ///J,13,53
        ///K,14,54
        ///L,15,55
        ///M,16,56
        ///N,17,57
        ///O,18,58
        ///P,19,59
        ///Q,20,60
        ///R,21,61
        ///S,22,62
        ///T,23,63
        ///U,24,64
        ///V,25,65
        ///W,26,66
        ///X,27,67
        ///Y,28,68
        ///Z,29,69
        ///1,30,35
        ///2,31,36
        ///3,32,37
        ///4,33,38
        ///5,34,39
        ///6,35,40
        ///7,36,41
        ///8,37,42
        ///9,38,43
        ///0,39,34
        ///Escape,41,13
        ///Backspace,42,2
        ///Tab,43,3
        ///Space,44,18
        ///Minus,45,143
        ///Equals,46,141
        ///LeftBracket,47,149
        ///RightBracket,48,151
        ///Backslash,49,150
        ///Semicolon,51,140
        ///Quote,52,152
        ///Grave,53,14 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyMap_txt {
            get {
                return ResourceManager.GetString("KeyMap_txt", resourceCulture);
            }
        }
    }
}
